update stack-new to use lib/app templates

diff --git a/bin/stack-new b/bin/stack-new
--- a/bin/stack-new
+++ b/bin/stack-new
@@ -4,8 +4,8 @@
 # TODO: figure out how to turn this into a stack template
 #
 
-if [ "$#" -ne 1 ]; then
-  echo "usage: stack-new NAME"
+if [ "$#" -ne 2 ]; then
+  echo "usage: stack-new [app|lib] NAME"
   echo ""
   echo "  NAME - a lower case hyphenated package name"
   echo ""
@@ -13,7 +13,11 @@ if [ "$#" -ne 1 ]; then
 fi
 
 # the package name is hyphenated lower case
-PACKAGE_NAME=${1,,}
+PACKAGE_TYPE=${1,,}
+
+# the package name is hyphenated lower case
+PACKAGE_NAME=${2,,}
+
 
 # The module name is upper camel cased.  This mess
 # splits the package name on hyphens, then appends
@@ -38,8 +42,12 @@ if [[ -e $PACKAGE_NAME ]]; then
 fi
 mkdir $PACKAGE_NAME
 cd $PACKAGE_NAME
-mkdir "src" "app" "test"
 
+mkdir "src" "test"
+
+
+case $PACKAGE_TYPE in
+  lib)
 #
 # create the cabal file
 #
@@ -54,6 +62,10 @@ maintainer:            ${USER_EMAIL}
 build-type:            Simple
 cabal-version:         >=1.10
 
+source-repository head
+  type:               git
+  location:           https://github.com/$USER/$PACKAGE_NAME
+
 library
   default-language:    Haskell2010
   hs-source-dirs:      src
@@ -63,32 +75,61 @@ library
                        "-with-rtsopts=-N"
   build-depends:       base                    >= 4.8
 
-
-executable $PACKAGE_NAME-app
+test-suite $PACKAGE_NAME-test
+  type:                exitcode-stdio-1.0
   default-language:    Haskell2010
-  hs-source-dirs:      app
+  hs-source-dirs:      test
+                       , src
+  main-is:             Test.hs
+  build-depends:       base
+                       , hspec
+                       , QuickCheck
+EOF
+;;
+  app)
+#
+# create the cabal file
+#
+cat << EOF > $PACKAGE_NAME.cabal
+name:                  $PACKAGE_NAME
+version:               0.0.1
+homepage:              https://github.com/$USER
+license:               ISC
+license-file:          LICENSE
+author:                ${USER_NAME}
+maintainer:            ${USER_EMAIL}
+build-type:            Simple
+cabal-version:         >=1.10
+
+source-repository head
+  type:               git
+  location:           https://github.com/$USER/$PACKAGE_NAME
+
+executable hello
+  default-language:    Haskell2010
+  hs-source-dirs:      src
   main-is:             Main.hs
+  other-modules:       Foo
   ghc-options:         -O2
                        -threaded
                        "-with-rtsopts=-N"
   build-depends:       base                    >= 4.8
-                       , $PACKAGE_NAME
 
 test-suite $PACKAGE_NAME-test
   type:                exitcode-stdio-1.0
   default-language:    Haskell2010
   hs-source-dirs:      test
-  main-is:             Spec.hs
+                       , src
+  main-is:             Test.hs
   build-depends:       base
-                       , $PACKAGE_NAME
                        , hspec
                        , QuickCheck
-
-source-repository head
-  type:               git
-  location:           https://github.com/$USER/$PACKAGE_NAME
 EOF
-
+;;
+*)
+  echo "unknown package type"
+  exit
+esac
 
 
 #
@@ -195,6 +236,8 @@ EOF
 #
 # create sample source files
 #
+case $PACKAGE_TYPE in
+  lib)
 cat << EOF > src/$MODULE_NAME.hs
 module $MODULE_NAME
     ( foo
@@ -203,27 +246,50 @@ module $MODULE_NAME
 foo :: String
 foo = "foo"
 EOF
+    ;;
+  app)
+cat << EOF > src/Foo.hs
+module Foo
+    ( foo
+    ) where
+
+foo :: String
+foo = "foo"
+EOF
+    ;;
+  *)
+    echo "error, uknown package type"
+    exit 1
+esac
 
 #
 # create application
 #
-cat << EOF > app/Main.hs 
+if [[ $PACKAGE_TYPE == 'app' ]]; then
+cat << EOF > src/Main.hs
 module Main where
 
-import $MODULE_NAME (foo)
+import Foo (foo)
 
 main = putStrLn foo
 EOF
+fi
+
+if [[ $PACKAGE_TYPE == 'app' ]]; then
+TEST_MODULE_NAME="Foo"
+else
+TEST_MODULE_NAME=$MODULE_NAME
+fi
 
 #
 # create application
 #
-cat << EOF > test/Spec.hs 
+cat << EOF > test/Test.hs
 import Test.Hspec
 import Test.QuickCheck
 import Control.Exception (evaluate)
 
-import $MODULE_NAME
+import $TEST_MODULE_NAME
 
 main :: IO ()
 main = hspec $ do
